language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - roxygen2

before_install:
  - Rscript -e "update.packages(ask = FALSE)"

before_script:
  - Rscript -e "devtools::document()"
  - Rscript -e "devtools::build_vignettes()"

# Only report coverage for the release version
after_success:
- test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'