language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel

before_install:
  - Rscript -e "update.packages(ask = FALSE)"
  - Rscript -e "if (!'covr' %in% rownames(installed.packages())) install.packages('covr')"
  - Rscript -e "if (!'roxygen2' %in% rownames(installed.packages())) install.packages('roxygen2')"
  - Rscript -e "if (!'rmarkdown' %in% rownames(installed.packages())) install.packages('rmarkdown')"

before_script:
  - Rscript -e "devtools::document()"
  - Rscript -e "devtools::build_vignettes()"

# Only report coverage for the release version
after_success:
- test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
